In [48]:
import pandas as pd

In [49]:
datar = pd.read_csv('../data/processed/paes_valdivia.csv')
datar

,anio,establecimiento,rbd,prueba,promedio
0,2024,Escuela Hospitalaria Puerto Montt\nRama,20409-310,Lenguaje,479.0
1,2024,Escuela Hospitalaria Puerto Montt\nRama,20409-310,M1,480.7
2,2024,Escuela Hospitalaria Puerto Montt\nRama,20409-310,M2,0.0
3,2024,Escuela Hospitalaria Puerto Montt\nRama,20409-310,Historia,447.0
4,2024,Escuela Hospitalaria Puerto Montt\nRama,20409-310,Ciencias,379.5
...,...,...,...,...,...
2791,2026,Colegio Roberto White Gesell\nRama,8339-310,M1,579.6
2792,2026,Colegio Roberto White Gesell\nRama,8339-310,M2,438.0
2793,2026,Colegio Roberto White Gesell\nRama,8339-310,Historia,443.4
2794,2026,Colegio Roberto White Gesell\nRama,8339-310,Ciencias,412.7
2795,2026,Colegio Roberto White Gesell\nRama,8339-310,Obligatoria,564.1

In [50]:
import pandas as pd

datar = pd.read_csv('../data/processed/paes_valdivia.csv')

# Asegurar string
datar["rbd"] = datar["rbd"].astype(str)

# 1️⃣ Guardar el rbd original en exrbd
datar["exrbd"] = datar["rbd"]

# 2️⃣ Limpiar rbd (quedarse solo antes del "-")
datar["rbd"] = (
    datar["rbd"]
    .str.split("-")
    .str[0]
    .str.strip()
)

# Guardar
datar.to_csv("../data/processed/paes_valdivia_limpio.csv", index=False)

datar.head()

,anio,establecimiento,rbd,prueba,promedio,exrbd
0,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,Lenguaje,479.0,20409-310
1,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,M1,480.7,20409-310
2,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,M2,0.0,20409-310
3,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,Historia,447.0,20409-310
4,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,Ciencias,379.5,20409-310

In [51]:


datac = pd.read_csv('../data/colegios/establecimientos_mineduc.csv', sep=';')
datac
datac_subset = datac[["RBD", "DGV_RBD", "NOM_RBD", "NOM_COM_RBD", "LATITUD", "LONGITUD"]]
datac_subset.head(12)

,RBD,DGV_RBD,NOM_RBD,NOM_COM_RBD,LATITUD,LONGITUD
0,1,9,LICEO POLITECNICO ARICA,ARICA,"-18,4872","-70,295212"
1,2,7,PARVULARIO LAS ESPIGUITAS,ARICA,"-18,46986198","-70,30275726"
2,3,5,ESC. PEDRO VICENTE GUTIERREZ TORRES,ARICA,"-18,50358009","-70,26082611"
3,4,3,LICEO OCTAVIO PALMA PEREZ,ARICA,"-18,474239","-70,308273"
4,5,1,JOVINA NARANJO FERNANDEZ,ARICA,"-18,4769","-70,313454"
5,7,8,L. POLI. BICENTENARIO DE EXCELENCIA ANTONIO VA...,ARICA,"-18,476151","-70,288368"
6,8,6,COLEGIO EDUARDO FREI MONTALVA,ARICA,"-18,482491","-70,317581"
7,9,4,ESCUELA REPUBLICA DE ISRAEL,ARICA,"-18,486691","-70,30452"
8,10,8,ESCUELA REPUBLICA DE FRANCIA,ARICA,"-18,474369","-70,309036"
9,11,6,ESC. GRAL. PEDRO LAGOS MARCHANT,ARICA,"-18,491011","-70,311577"
10,12,4,ESCUELA GRAL JOSE MIGUEL CARRERA,ARICA,"-18,49193","-70,293968"
11,13,2,ESCUELA MANUEL RODRIGUEZ ERDOYZA,ARICA,"-18,48134","-70,285347"

In [52]:
# Filtrar filas por valor exacto
valdivia = datac_subset[datac_subset["NOM_COM_RBD"] == "VALDIVIA"]
valdivia

,RBD,DGV_RBD,NOM_RBD,NOM_COM_RBD,LATITUD,LONGITUD
5560,6751,2,INSTITUTO COMERCIAL DE VALDIVIA,VALDIVIA,"-39,817619","-73,246964"
5561,6752,0,LICEO TECNICO VALDIVIA,VALDIVIA,"-39,82925","-73,221237"
5562,6753,9,LICEO SANTA MARIA LA BLANCA,VALDIVIA,"-39,81601","-73,240768"
5563,6754,7,LICEO ARMANDO ROBLES RIVERA,VALDIVIA,"-39,81567","-73,242622"
5564,6755,5,LICEO INDUSTRIAL VALDIVIA,VALDIVIA,"-39,831871","-73,220757"
...,...,...,...,...,...,...
16566,42067,0,INDEPENDENCIA,VALDIVIA,,
16568,42072,7,JARDIN INFANTIL ESTRELLITA NUESTRA,VALDIVIA,,
16647,42202,9,ALTO GUACAMAYO,VALDIVIA,,
16667,42248,7,SALA CUNA Y JARDIN INFANTIL MIS HUELLAS,VALDIVIA,,
16669,42250,9,CLUB DEL BOSQUE VALDIVIANO,VALDIVIA,"-39,80966719","-73,25952667"

In [53]:
paes = pd.read_csv("../data/processed/paes_valdivia_limpio.csv")
mineduc = pd.read_csv("../data/colegios/establecimientos_mineduc.csv", sep=';')

print(paes["rbd"].head())
print(mineduc["RBD"].head())

print(paes["rbd"].dtype, mineduc["RBD"].dtype)

0    20409
1    20409
2    20409
3    20409
4    20409
Name: rbd, dtype: int64
0    1
1    2
2    3
3    4
4    5
Name: RBD, dtype: int64
int64 int64

In [54]:
paes["rbd"] = paes["rbd"].astype(str).str.strip()
mineduc["rbd"] = mineduc["RBD"].astype(str).str.strip()

In [55]:
paes_geo = paes.merge(
    mineduc[["rbd", "NOM_RBD", "LATITUD", "LONGITUD"]],
    on="rbd",
    how="left"
)

sin_coord = paes_geo["LATITUD"].isna().sum()

print(f"Colegios sin coordenadas: {sin_coord}")


paes_geo.to_csv(
    "../data/processed/paes_valdivia_geo.csv",
    index=False
)

Colegios sin coordenadas: 0

In [56]:
paes_geo

,anio,establecimiento,rbd,prueba,promedio,exrbd,NOM_RBD,LATITUD,LONGITUD
0,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,Lenguaje,479.0,20409-310,ESCUELA HOSPITALARIA PUERTO MONTT,"-41,44917","-72,95726"
1,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,M1,480.7,20409-310,ESCUELA HOSPITALARIA PUERTO MONTT,"-41,44917","-72,95726"
2,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,M2,0.0,20409-310,ESCUELA HOSPITALARIA PUERTO MONTT,"-41,44917","-72,95726"
3,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,Historia,447.0,20409-310,ESCUELA HOSPITALARIA PUERTO MONTT,"-41,44917","-72,95726"
4,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,Ciencias,379.5,20409-310,ESCUELA HOSPITALARIA PUERTO MONTT,"-41,44917","-72,95726"
...,...,...,...,...,...,...,...,...,...
2791,2026,Colegio Roberto White Gesell\nRama,8339,M1,579.6,8339-310,COLEGIO ROBERTO WHITE GESELL,"-43,617519","-71,806374"
2792,2026,Colegio Roberto White Gesell\nRama,8339,M2,438.0,8339-310,COLEGIO ROBERTO WHITE GESELL,"-43,617519","-71,806374"
2793,2026,Colegio Roberto White Gesell\nRama,8339,Historia,443.4,8339-310,COLEGIO ROBERTO WHITE GESELL,"-43,617519","-71,806374"
2794,2026,Colegio Roberto White Gesell\nRama,8339,Ciencias,412.7,8339-310,COLEGIO ROBERTO WHITE GESELL,"-43,617519","-71,806374"
2795,2026,Colegio Roberto White Gesell\nRama,8339,Obligatoria,564.1,8339-310,COLEGIO ROBERTO WHITE GESELL,"-43,617519","-71,806374"

In [57]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
from pathlib import Path

# =========================
# RUTAS
# =========================
INPUT = Path("../data/processed/paes_valdivia_geo.csv")
OUTPUT = Path("../data/processed/paes_valdivia.geojson")



# =========================
# CARGA
# =========================
df = pd.read_csv(INPUT)

# =========================
# LIMPIEZA COORDENADAS
# =========================
df["LATITUD"] = (
    df["LATITUD"]
    .astype(str)
    .str.replace(",", ".", regex=False)
    .astype(float)
)

df["LONGITUD"] = (
    df["LONGITUD"]
    .astype(str)
    .str.replace(",", ".", regex=False)
    .astype(float)
)


# Seguridad básica
df = df.dropna(subset=["LATITUD", "LONGITUD"])

# =========================
# CREAR GEOMETRÍA
# =========================
geometry = [
    Point(xy) for xy in zip(df["LONGITUD"], df["LATITUD"])
]

gdf = gpd.GeoDataFrame(
    df,
    geometry=geometry,
    crs="EPSG:4326"
)

# =========================
# EXPORTAR A GEOJSON
# =========================
gdf.to_file(
    OUTPUT,
    driver="GeoJSON",
    encoding="utf-8"
)

print("✅ GeoJSON creado correctamente")
print(f"📍 Archivo: {OUTPUT}")
print(f"🔢 Registros: {len(gdf)}")

✅ GeoJSON creado correctamente
📍 Archivo: ..\data\processed\paes_valdivia.geojson
🔢 Registros: 2796

In [58]:
gdf["rbd"] = (
    gdf["rbd"]
    .astype(str)
    .str.split("-")
    .str[0]
)

In [59]:
gdf_pivot = gdf.pivot_table(
    index=["rbd", "NOM_RBD", "geometry", "exrbd"],
    columns="prueba",
    values="promedio",
    aggfunc="mean"
).reset_index()
gdf_pivot

prueba,rbd,NOM_RBD,geometry,exrbd,Ciencias,Historia,Lenguaje,M1,M2,Obligatoria
0,11554,ESCUELA DE ADULTOS DE RIO BUENO,POINT (-72.96240 -40.33508),11554-363,402.0,486.0,477.0,508.0,0.0,492.5
1,11591,INSTITUTO TECNICO PROFESIONAL LLIFEN,POINT (-72.25870 -40.19814),11591-310,380.0,496.5,573.1,543.4,388.0,558.3
2,11591,INSTITUTO TECNICO PROFESIONAL LLIFEN,POINT (-72.25870 -40.19814),11591-510,370.0,385.0,487.8,493.5,399.3,492.1
3,11591,INSTITUTO TECNICO PROFESIONAL LLIFEN,POINT (-72.25870 -40.19814),11591-610,388.2,412.7,513.0,521.1,389.1,519.2
4,12182,ESCUELA PARTICULAR N.303 LUIS CRUZ MARTINEZ,POINT (-73.17784 -40.58707),12182-363,452.0,0.0,605.0,738.0,378.0,671.5
...,...,...,...,...,...,...,...,...,...,...
461,8255,LICEO RAYEN MAPU,POINT (-73.62377 -43.11462),8255-610,452.3,480.8,567.1,559.0,376.5,570.0
462,8309,LICEO PENINSULAR AYACARA,POINT (-72.78697 -42.30840),8309-310,436.4,552.8,594.4,599.4,435.3,596.9
463,8310,COLEGIO MAURICIO HITCHCOCK,POINT (-72.71593 -41.80059),8310-310,429.3,463.4,586.2,563.1,366.3,574.6
464,8331,LICEO BICENTENARIO FUTALEUFU,POINT (-71.87028 -43.18415),8331-310,407.1,457.7,544.0,592.4,385.4,572.1
465,8339,COLEGIO ROBERTO WHITE GESELL,POINT (-71.80637 -43.61752),8339-310,412.7,443.4,544.4,579.6,438.0,564.1

In [ ]:
import geopandas as gpd

gdf_colegios = gpd.GeoDataFrame(
    gdf_pivot,
    geometry="geometry",
    crs="EPSG:4326"
)
gdf_colegios

In [61]:
print("Colegios únicos:", gdf_colegios["rbd"].nunique())
print("Filas totales:", len(gdf_colegios))

Colegios únicos: 312
Filas totales: 466

In [62]:
gdf_colegios.to_file(
    "../data/processed/colegios_paes_valdivia.geojson",
    driver="GeoJSON"
)

print("✅ GeoJSON consolidado por RBD creado correctamente")

✅ GeoJSON consolidado por RBD creado correctamente