In [1]:
import pandas as pd

In [2]:
datar = pd.read_csv('../data/processed/paes_valdivia.csv')
datar.head(15)

# Limpiar RBD: quedarse solo con lo anterior al "-"
datar["rbd"] = (
    datar["rbd"]
    .astype(str)
    .str.split("-")
    .str[0]
)

# Guardar archivo limpio
datar.to_csv("../data/processed/paes_valdivia_limpio.csv", index=False)
datar

,anio,establecimiento,rbd,prueba,promedio
0,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,Lenguaje,479.0
1,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,M1,480.7
2,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,M2,0.0
3,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,Historia,447.0
4,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,Ciencias,379.5
...,...,...,...,...,...
2791,2026,Colegio Roberto White Gesell\nRama,8339,M1,579.6
2792,2026,Colegio Roberto White Gesell\nRama,8339,M2,438.0
2793,2026,Colegio Roberto White Gesell\nRama,8339,Historia,443.4
2794,2026,Colegio Roberto White Gesell\nRama,8339,Ciencias,412.7
2795,2026,Colegio Roberto White Gesell\nRama,8339,Obligatoria,564.1

In [3]:


datac = pd.read_csv('../data/colegios/establecimientos_mineduc.csv', sep=';')
datac
datac_subset = datac[["RBD", "DGV_RBD", "NOM_RBD", "NOM_COM_RBD", "LATITUD", "LONGITUD"]]
datac_subset.head(12)

,RBD,DGV_RBD,NOM_RBD,NOM_COM_RBD,LATITUD,LONGITUD
0,1,9,LICEO POLITECNICO ARICA,ARICA,"-18,4872","-70,295212"
1,2,7,PARVULARIO LAS ESPIGUITAS,ARICA,"-18,46986198","-70,30275726"
2,3,5,ESC. PEDRO VICENTE GUTIERREZ TORRES,ARICA,"-18,50358009","-70,26082611"
3,4,3,LICEO OCTAVIO PALMA PEREZ,ARICA,"-18,474239","-70,308273"
4,5,1,JOVINA NARANJO FERNANDEZ,ARICA,"-18,4769","-70,313454"
5,7,8,L. POLI. BICENTENARIO DE EXCELENCIA ANTONIO VA...,ARICA,"-18,476151","-70,288368"
6,8,6,COLEGIO EDUARDO FREI MONTALVA,ARICA,"-18,482491","-70,317581"
7,9,4,ESCUELA REPUBLICA DE ISRAEL,ARICA,"-18,486691","-70,30452"
8,10,8,ESCUELA REPUBLICA DE FRANCIA,ARICA,"-18,474369","-70,309036"
9,11,6,ESC. GRAL. PEDRO LAGOS MARCHANT,ARICA,"-18,491011","-70,311577"
10,12,4,ESCUELA GRAL JOSE MIGUEL CARRERA,ARICA,"-18,49193","-70,293968"
11,13,2,ESCUELA MANUEL RODRIGUEZ ERDOYZA,ARICA,"-18,48134","-70,285347"

In [4]:
# Filtrar filas por valor exacto
valdivia = datac_subset[datac_subset["NOM_COM_RBD"] == "VALDIVIA"]
valdivia

,RBD,DGV_RBD,NOM_RBD,NOM_COM_RBD,LATITUD,LONGITUD
5560,6751,2,INSTITUTO COMERCIAL DE VALDIVIA,VALDIVIA,"-39,817619","-73,246964"
5561,6752,0,LICEO TECNICO VALDIVIA,VALDIVIA,"-39,82925","-73,221237"
5562,6753,9,LICEO SANTA MARIA LA BLANCA,VALDIVIA,"-39,81601","-73,240768"
5563,6754,7,LICEO ARMANDO ROBLES RIVERA,VALDIVIA,"-39,81567","-73,242622"
5564,6755,5,LICEO INDUSTRIAL VALDIVIA,VALDIVIA,"-39,831871","-73,220757"
...,...,...,...,...,...,...
16566,42067,0,INDEPENDENCIA,VALDIVIA,,
16568,42072,7,JARDIN INFANTIL ESTRELLITA NUESTRA,VALDIVIA,,
16647,42202,9,ALTO GUACAMAYO,VALDIVIA,,
16667,42248,7,SALA CUNA Y JARDIN INFANTIL MIS HUELLAS,VALDIVIA,,
16669,42250,9,CLUB DEL BOSQUE VALDIVIANO,VALDIVIA,"-39,80966719","-73,25952667"

In [5]:
paes = pd.read_csv("../data/processed/paes_valdivia_limpio.csv")
mineduc = pd.read_csv("../data/colegios/establecimientos_mineduc.csv", sep=';')

print(paes["rbd"].head())
print(mineduc["RBD"].head())

print(paes["rbd"].dtype, mineduc["RBD"].dtype)

0    20409
1    20409
2    20409
3    20409
4    20409
Name: rbd, dtype: int64
0    1
1    2
2    3
3    4
4    5
Name: RBD, dtype: int64
int64 int64

In [6]:
paes["rbd"] = paes["rbd"].astype(str).str.strip()
mineduc["rbd"] = mineduc["RBD"].astype(str).str.strip()

In [7]:
paes_geo = paes.merge(
    mineduc[["rbd", "LATITUD", "LONGITUD"]],
    on="rbd",
    how="left"
)

sin_coord = paes_geo["LATITUD"].isna().sum()

print(f"Colegios sin coordenadas: {sin_coord}")


paes_geo.to_csv(
    "../data/processed/paes_valdivia_geo.csv",
    index=False
)

Colegios sin coordenadas: 0

In [8]:
paes_geo

,anio,establecimiento,rbd,prueba,promedio,LATITUD,LONGITUD
0,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,Lenguaje,479.0,"-41,44917","-72,95726"
1,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,M1,480.7,"-41,44917","-72,95726"
2,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,M2,0.0,"-41,44917","-72,95726"
3,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,Historia,447.0,"-41,44917","-72,95726"
4,2024,Escuela Hospitalaria Puerto Montt\nRama,20409,Ciencias,379.5,"-41,44917","-72,95726"
...,...,...,...,...,...,...,...
2791,2026,Colegio Roberto White Gesell\nRama,8339,M1,579.6,"-43,617519","-71,806374"
2792,2026,Colegio Roberto White Gesell\nRama,8339,M2,438.0,"-43,617519","-71,806374"
2793,2026,Colegio Roberto White Gesell\nRama,8339,Historia,443.4,"-43,617519","-71,806374"
2794,2026,Colegio Roberto White Gesell\nRama,8339,Ciencias,412.7,"-43,617519","-71,806374"
2795,2026,Colegio Roberto White Gesell\nRama,8339,Obligatoria,564.1,"-43,617519","-71,806374"

In [9]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
from pathlib import Path

# =========================
# RUTAS
# =========================
INPUT = Path("../data/processed/paes_valdivia_geo.csv")
OUTPUT = Path("../data/processed/paes_valdivia.geojson")



# =========================
# CARGA
# =========================
df = pd.read_csv(INPUT)

# =========================
# LIMPIEZA COORDENADAS
# =========================
df["LATITUD"] = (
    df["LATITUD"]
    .astype(str)
    .str.replace(",", ".", regex=False)
    .astype(float)
)

df["LONGITUD"] = (
    df["LONGITUD"]
    .astype(str)
    .str.replace(",", ".", regex=False)
    .astype(float)
)


# Seguridad básica
df = df.dropna(subset=["LATITUD", "LONGITUD"])

# =========================
# CREAR GEOMETRÍA
# =========================
geometry = [
    Point(xy) for xy in zip(df["LONGITUD"], df["LATITUD"])
]

gdf = gpd.GeoDataFrame(
    df,
    geometry=geometry,
    crs="EPSG:4326"
)

# =========================
# EXPORTAR A GEOJSON
# =========================
gdf.to_file(
    OUTPUT,
    driver="GeoJSON",
    encoding="utf-8"
)

print("✅ GeoJSON creado correctamente")
print(f"📍 Archivo: {OUTPUT}")
print(f"🔢 Registros: {len(gdf)}")

✅ GeoJSON creado correctamente
📍 Archivo: ..\data\processed\paes_valdivia.geojson
🔢 Registros: 2796

In [10]:
gdf["rbd"] = (
    gdf["rbd"]
    .astype(str)
    .str.split("-")
    .str[0]
)

In [11]:
gdf_pivot = gdf.pivot_table(
    index=["rbd", "establecimiento", "geometry"],
    columns="prueba",
    values="promedio",
    aggfunc="mean"
).reset_index()
gdf_pivot

prueba,rbd,establecimiento,geometry,Ciencias,Historia,Lenguaje,M1,M2,Obligatoria
0,11554,Escuela De Adultos De Rio Bueno\nRama,POINT (-72.96240 -40.33508),402.000000,486.00,477.000000,508.000000,0.000000,492.500000
1,11591,Instituto Tecnico Profesional Llifen\nRama,POINT (-72.25870 -40.19814),379.400000,431.40,524.633333,519.333333,392.133333,523.200000
2,12182,Escuela Particular N,POINT (-73.17784 -40.58707),452.000000,0.00,605.000000,738.000000,378.000000,671.500000
3,12183,Colegio Saint Thomas College\nRama,POINT (-73.10551 -40.58920),506.300000,586.60,674.000000,732.400000,547.700000,710.000000
4,12185,Colegio Bicentenario Helvecia\nRama,POINT (-73.21696 -39.84378),415.200000,454.25,543.300000,529.700000,211.200000,541.350000
...,...,...,...,...,...,...,...,...,...
308,8255,Liceo Rayen Mapu\nRama,POINT (-73.62377 -43.11462),423.933333,476.00,570.900000,564.666667,394.500000,570.133333
309,8309,Liceo Peninsular Ayacara\nRama,POINT (-72.78697 -42.30840),436.400000,552.80,594.400000,599.400000,435.300000,596.900000
310,8310,Colegio Mauricio Hitchcock\nRama,POINT (-72.71593 -41.80059),429.300000,463.40,586.200000,563.100000,366.300000,574.600000
311,8331,Liceo Bicentenario Futaleufu\nRama,POINT (-71.87028 -43.18415),407.100000,457.70,544.000000,592.400000,385.400000,572.100000
312,8339,Colegio Roberto White Gesell\nRama,POINT (-71.80637 -43.61752),412.700000,443.40,544.400000,579.600000,438.000000,564.100000

In [12]:
import geopandas as gpd

gdf_colegios = gpd.GeoDataFrame(
    gdf_pivot,
    geometry="geometry",
    crs="EPSG:4326"
)

In [13]:
print("Colegios únicos:", gdf_colegios["rbd"].nunique())
print("Filas totales:", len(gdf_colegios))

Colegios únicos: 312
Filas totales: 313

In [14]:
gdf_colegios.to_file(
    "../data/processed/colegios_paes_valdivia.geojson",
    driver="GeoJSON"
)

print("✅ GeoJSON consolidado por RBD creado correctamente")

✅ GeoJSON consolidado por RBD creado correctamente